version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing Terraform...
      - sudo yum install -y yum-utils shadow-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform

  pre_build:
    commands:
      - echo Logging into AWS...
      - terraform --version
      - terraform init
      - docker --version 
  build:
    commands:
      - echo Provisioning EC2...
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan